### ISSUE TITLE
Meta-Tutorial Presentations of BB+ Dev Forum

### ISSUE THREAD

**Issue by antoine-lizee** [jmandel/bb-tutorial-growthtastic#1]
Sorry to put that here, it's kind of a blaspheme for a dev, but is there any place we could find Ryan's presentations? Especially the ones before the start of your (amazing)  tutorial...

Thanks a lot!
Antoine

**Comment by jmandel** [comment]
Hi Antoine,

Here works as well as anywhere :-)

We'll get Ryan's presentation linked to directly from the tutorial (and I'll keep this issue open until we do).

**Comment by antoine-lizee** [comment]
Amazing, thanks!

2013/7/17 Josh Mandel notifications@github.com

**Comment by jmandel** [comment]
OK, link added to top of:
https://github.com/jmandel/bb-tutorial-growthtastic/wiki/Push

(Link is: https://docs.google.com/file/d/1aPkFzv_R0GJcgKYhG7ki8Qc0PiGQnIClUEkTPxm4XxyhxOLlB6pv7rO7JPUK/view)
